name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        defaults:
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              working-directory: ./cards-app
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm start
